# Converts the markdown file in ./entries into LaTeX, then moves it to LaTeX dir
build: $(wildcard ./entries/*.md)
	./pandoc/convert.sh $?
	mv -t ./latex/entries/ $(addsuffix .tex, $(basename $?))
	$(MAKE) -C latex/

clean:
	$(MAKE) -C latex/ clean

# Deletes the autogenerated latex files.
delete: $(wildcard ./latex/entries/*.tex)
	rm $?
	$(MAKE) -C latex/ delete